### PR TITLE
Bug fixes

### LINKED ISSUE #139: Bugs identified during facilitator testing

### PR DESCRIPTION
**Pull request by sarvesh-ost**
fixes #139

### CODE REVIEW

File: src/subscriptions/TransactionFetcher.ts [hunk 1]
```diff
@@ -55,15 +55,14 @@ export default class TransactionFetcher {
       const variables = {
         contractAddress: entityRecord.contractAddress,
         uts,
-        limit: this.queryLimit,
```
Comment (puneet-khushwani-eth) [inline src/subscriptions/TransactionFetcher.ts]: It seems that we have 2 sources of truth for `this.queryLimit`. In `src/GraphQueries/FetchQueries.ts` we have hardcoded `first: 100` in all queries. Ideally even this `100` should come from a query param.

File: src/handlers/Handlers.ts [hunk 2]
```diff
@@ -21,6 +21,7 @@ import ProveGatewayHandler from './ProveGatewayHandler';
 import StakeIntentDeclareHandler from './StakeIntentDeclareHandler';
 import StakeProgressHandler from './StakeProgressHandler';
 import StakeRequestHandler from './StakeRequestHandler';
+import StakeIntentConfirmHandler from "./StakeIntentConfirmHandler";
```
Comment (puneet-khushwani-eth) [inline src/handlers/Handlers.ts]: linter issues

File: test/handlers/StakeRequestedHandler/persist.test.ts [hunk 3]
```diff
@@ -19,7 +19,8 @@ describe('StakeRequestedHandler.persist()', (): void => {
       gasLimit: '1',
       nonce: '1',
       gateway: '0xF1e701FbE4288a38FfFEa3084C826B810c5d5294',
-      stakerProxy: '0xE1e701FbE4288a38FfFEa3084C826B810c5d5294',
+      staker: '0xE1e701FbE4288a38FfFEa3084C826B810c5d5294',
```
Comment (puneet-khushwani-eth) [inline test/handlers/StakeRequestedHandler/persist.test.ts]: I guess we had a discussion to not use actual addresses until must.

File: src/bin/facilitator-init.ts [hunk 4]
```diff
@@ -5,7 +5,10 @@ import Account from '../Account';
 import { Chain, FacilitatorConfig } from '../Config/Config';
 import DatabaseFileHelper from '../DatabaseFileHelper';
 import Logger from '../Logger';
-import Utils from '../Utils';
+import MosaicConfig from '../Config/MosaicConfig';
+// import { Config, ENV_WORKER_PASSWORD_PREFIX } from '../Config/Config';
+// import Repositories from '../repositories/Repositories';
+// import SeedData from '../SeedData';
```
Comment (deepesh-kn) [inline src/bin/facilitator-init.ts]: Remove commented code.

File: src/bin/facilitator-init.ts [hunk 5]
```diff
@@ -93,17 +96,29 @@ commander
     facilitatorConfig.database.path = dbPath;
     facilitatorConfig.originChain = originChainId;
     facilitatorConfig.auxChainId = options.chainId;
-    const setFacilitator = (chainId: string, rpc: string, password: string): void => {
+    const setFacilitator = (chainid: string, rpc: string, password: string): void => {
```
Comment (deepesh-kn) [inline src/bin/facilitator-init.ts]: Why?

File: src/bin/facilitator-init.ts [hunk 6]
```diff
@@ -93,17 +96,29 @@ commander
...
       const account: Account = Account.create(new Web3(null), password);
 
-      facilitatorConfig.chains[chainId] = new Chain(rpc, account.address);
+      facilitatorConfig.chains[chainid] = new Chain(rpc, account.address);
+      // const envVariableNameForWorkerPassword = `${ENV_WORKER_PASSWORD_PREFIX}${account.address}`;
+      // process.env[envVariableNameForWorkerPassword] = password;
```
Comment (deepesh-kn) [inline src/bin/facilitator-init.ts]: Remove commented code.

File: src/bin/facilitator-init.ts [hunk 7]
```diff
@@ -93,17 +96,29 @@ commander
...
 
+    // const config = new Config(mosaicConfig, facilitatorConfig);
+    // const repositories = await Repositories.create(config.facilitator.database.path);
+    // const seedData = new SeedData(
+    //   config,
+    //   repositories.gatewayRepository,
+    //   repositories.auxiliaryChainRepository,
+    //   repositories.contractEntityRepository,
+    // );
+    // await seedData.populateDb();
```
Comment (deepesh-kn) [inline src/bin/facilitator-init.ts]: Please check if this code should be commented? When is seed data populated?
If yes, then please delete it.

**Comment by abhayks1** [comment]
Reviewing...

File: src/subscriptions/TransactionFetcher.ts (hunk 1 above)
Comment (abhayks1) [reply src/subscriptions/TransactionFetcher.ts]: Agreed. Fetch queries needs to be updated to render from limit parameter.

File: src/bin/facilitator-init.ts (hunk 4 above)
Comment (puneet-khushwani-eth) [reply src/bin/facilitator-init.ts]: This code will be used to populate seedData. We can not this open up till we have dev chains and our integration test don't start using it.

File: src/bin/facilitator-init.ts (hunk 6 above)
Comment (puneet-khushwani-eth) [reply src/bin/facilitator-init.ts]: similar to above

File: src/bin/facilitator-init.ts (hunk 7 above)
Comment (puneet-khushwani-eth) [reply src/bin/facilitator-init.ts]: We can not this open up till we have dev chains and our integration test don't start using it. Keeping it here so that we can just uncomment it later and can also test now by manually uncommenting and running it.

Comment (puneet-khushwani-eth) [reply src/bin/facilitator-init.ts]: Will also write a note in the ticket we have for integration tests to open this up.

File: src/services/ProgressService.ts [hunk 8]
```diff
@@ -100,11 +90,11 @@ export default class ProgressService {
       gasPrice: ORIGIN_GAS_PRICE,
     };
 
-    assert(message.hashLock !== undefined);
+    assert(message.secret !== undefined);
```
Comment (abhayks1) [inline src/services/ProgressService.ts]: We can add assert message here.

File: src/bin/facilitator-init.ts (hunk 5 above)
Comment (puneet-khushwani-eth) [reply src/bin/facilitator-init.ts]: reverted this change.
